# Generated by Django 6.0.6 on 2026-06-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='username',
            new_name='name',
        ),
    ]
